function value = readParam_delim(ParamName,ParamFile,delimiter)
% Usage: value = readParam(ParamName,ParamFile,delimiter)
% Ricardo Fernández-Terán
% v1.0 - 2018-03-21

%% Main function to read the parameter
allParams   = importfile(ParamFile,delimiter);
rightRow    = strcmp(allParams, ParamName);
value       = allParams{fliplr(rightRow)};

%% Subroutine to import the file
    function options = importfile(filename, delimiter, startRow, endRow)
    %IMPORTFILE Import numeric data from a text file as a matrix.
    %   OPTIONS = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
    %   the default selection.
    %
    %   OPTIONS = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
    %   STARTROW through ENDROW of text file FILENAME.
    %
    % Example:
    %   options = importfile('options.txt', 1, 4);
    %
    %    See also TEXTSCAN.

    % Auto-generated by MATLAB on 2017/04/28 20:27:20

    %% Initialize variables.
    if nargin<=3
        startRow = 1;
        endRow = inf;
    end

    %% Read columns of data as text:
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%s%s%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end

    %% Close the text file.
    fclose(fileID);

    %% Convert the contents of columns containing numeric text to numbers.
    % Replace non-numeric text with NaN.
    raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
    for col=1:length(dataArray)-1
        raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
    end
    numericData = NaN(size(dataArray{1},1),size(dataArray,2));


    %% Split data into numeric and string columns.
    rawNumericColumns = {};
    rawStringColumns = string(raw(:, [1,2]));


    %% Create output variable
    raw(:,[1, 2]) = cellfun(@(x) cellstr(x), raw(:,[1, 2]));
    options = raw;